---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: Check if kibana is accessible
    assert:
      that:
        wait_for: host=localhost port=5601 timeout=3
        register: host_accessible
  - name: Check that the kibana.log exists
    assert:
      that:    
        stat:
          path: /var/logs/kibana.log
        register: stat_result
